name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v5
        env.production:
          NEXT_PUBLIC_DOMAIN: mytop-api
        with:
          registry: ghcr.io
          name: DenisJet/mytop-app/mytop-app
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
